export const CREATE_NEW_MESSAGE="CREATE_NEW_MESSAGE"
export const SET_ALL_MESSAGES="SET_ALL_MESSAGES"
export const ADD_NEW_MESSAGE="ADD_NEW_MESSAGE"
export const DELETE_SELECTED_MESSAGES="DELETE_SELECTED_MESSAGES"
